# File: .github/workflows/backend-ci.yml

name: Backend API CI/CD

on:
  push:
    branches:
      - main # Sesuaikan dengan nama branch utama Anda (misalnya: master)
    paths:
      - 'ToDo-React/back-end/**' # Hanya trigger jika file di folder backend berubah

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
  
jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./ToDo-React/back-end
          push: true
          # Tag: johanagustianpohan/todo-web-app-devops:backend-latest
          tags: ${{ env.DOCKER_USER }}/todo-web-app-devops:backend-latest